// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: kafka_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Тип действия пользователя
type ActionType int32

const (
	ActionType_ACTION_UNKNOWN       ActionType = 0
	ActionType_ACTION_CREATE_TASK   ActionType = 1 // Создание задачи
	ActionType_ACTION_DELETE_TASK   ActionType = 2 // Удаление задачи
	ActionType_ACTION_COMPLETE_TASK ActionType = 3 // Завершение задачи
	ActionType_ACTION_GET_TASKS     ActionType = 4 // Получение списка задач
)

// Enum value maps for ActionType.
var (
	ActionType_name = map[int32]string{
		0: "ACTION_UNKNOWN",
		1: "ACTION_CREATE_TASK",
		2: "ACTION_DELETE_TASK",
		3: "ACTION_COMPLETE_TASK",
		4: "ACTION_GET_TASKS",
	}
	ActionType_value = map[string]int32{
		"ACTION_UNKNOWN":       0,
		"ACTION_CREATE_TASK":   1,
		"ACTION_DELETE_TASK":   2,
		"ACTION_COMPLETE_TASK": 3,
		"ACTION_GET_TASKS":     4,
	}
)

func (x ActionType) Enum() *ActionType {
	p := new(ActionType)
	*p = x
	return p
}

func (x ActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_kafka_service_proto_enumTypes[0].Descriptor()
}

func (ActionType) Type() protoreflect.EnumType {
	return &file_kafka_service_proto_enumTypes[0]
}

func (x ActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActionType.Descriptor instead.
func (ActionType) EnumDescriptor() ([]byte, []int) {
	return file_kafka_service_proto_rawDescGZIP(), []int{0}
}

// Событие действия пользователя
type TaskEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Время, когда пользователь отправил запрос
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Действие пользователя
	Action ActionType `protobuf:"varint,2,opt,name=action,proto3,enum=checklist.ActionType" json:"action,omitempty"`
	// ID пользователя
	UserId string `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// ID задачи (опционально, для GetTasks может быть пустым)
	TaskId string `protobuf:"bytes,4,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	// Дополнительная информация о событии
	Details       string `protobuf:"bytes,5,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskEvent) Reset() {
	*x = TaskEvent{}
	mi := &file_kafka_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskEvent) ProtoMessage() {}

func (x *TaskEvent) ProtoReflect() protoreflect.Message {
	mi := &file_kafka_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskEvent.ProtoReflect.Descriptor instead.
func (*TaskEvent) Descriptor() ([]byte, []int) {
	return file_kafka_service_proto_rawDescGZIP(), []int{0}
}

func (x *TaskEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *TaskEvent) GetAction() ActionType {
	if x != nil {
		return x.Action
	}
	return ActionType_ACTION_UNKNOWN
}

func (x *TaskEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TaskEvent) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskEvent) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

var File_kafka_service_proto protoreflect.FileDescriptor

const file_kafka_service_proto_rawDesc = "" +
	"\n" +
	"\x13kafka_service.proto\x12\tchecklist\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc0\x01\n" +
	"\tTaskEvent\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12-\n" +
	"\x06action\x18\x02 \x01(\x0e2\x15.checklist.ActionTypeR\x06action\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x17\n" +
	"\atask_id\x18\x04 \x01(\tR\x06taskId\x12\x18\n" +
	"\adetails\x18\x05 \x01(\tR\adetails*\x80\x01\n" +
	"\n" +
	"ActionType\x12\x12\n" +
	"\x0eACTION_UNKNOWN\x10\x00\x12\x16\n" +
	"\x12ACTION_CREATE_TASK\x10\x01\x12\x16\n" +
	"\x12ACTION_DELETE_TASK\x10\x02\x12\x18\n" +
	"\x14ACTION_COMPLETE_TASK\x10\x03\x12\x14\n" +
	"\x10ACTION_GET_TASKS\x10\x04B\x06Z\x04.;pbb\x06proto3"

var (
	file_kafka_service_proto_rawDescOnce sync.Once
	file_kafka_service_proto_rawDescData []byte
)

func file_kafka_service_proto_rawDescGZIP() []byte {
	file_kafka_service_proto_rawDescOnce.Do(func() {
		file_kafka_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kafka_service_proto_rawDesc), len(file_kafka_service_proto_rawDesc)))
	})
	return file_kafka_service_proto_rawDescData
}

var file_kafka_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_kafka_service_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_kafka_service_proto_goTypes = []any{
	(ActionType)(0),               // 0: checklist.ActionType
	(*TaskEvent)(nil),             // 1: checklist.TaskEvent
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_kafka_service_proto_depIdxs = []int32{
	2, // 0: checklist.TaskEvent.timestamp:type_name -> google.protobuf.Timestamp
	0, // 1: checklist.TaskEvent.action:type_name -> checklist.ActionType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_kafka_service_proto_init() }
func file_kafka_service_proto_init() {
	if File_kafka_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kafka_service_proto_rawDesc), len(file_kafka_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kafka_service_proto_goTypes,
		DependencyIndexes: file_kafka_service_proto_depIdxs,
		EnumInfos:         file_kafka_service_proto_enumTypes,
		MessageInfos:      file_kafka_service_proto_msgTypes,
	}.Build()
	File_kafka_service_proto = out.File
	file_kafka_service_proto_goTypes = nil
	file_kafka_service_proto_depIdxs = nil
}
